#!/bin/bash

vpspackversion=3.6.5
OS=`uname -m`;
fecha=`date`;
MYIP=`hostname -I | awk '{print $1}'`;
MYIP2="s/xxxxxxxxx/$MYIP/g";
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "  \033[1;33mESPERE \033[1;37m- \033[1;33m["
while true; do
for((i=0; i<18; i++)); do
echo -ne "\033[1;31m#"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;33m]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  \033[1;33mESPERE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
if [ $(id -u) != 0 ]
then
echo "Ejecute el script como root"
exit
fi
clear
mkdir /etc/VpsPackdir  2>/dev/null
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m ───────────────────────────────────────\033[1;33m"
echo -e "\033[1;30mInstalando VPSPack $vpspackversion\033[0m"
echo -e "\033[1;30mEspere por favor\033[0m"
echo -e "\033[1;30mSe instalaran los paquetes necesarios\033[0m"
echo -e "\033[1;30mGrupo de Telegram: @PwrMX\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m ───────────────────────────────────────\033[1;33m"
sleep 5
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m Preparando Sistema\033[1;33m"
function preparar(){
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null
mkdir /etc/VpsPackdir/v 2>/dev/null
rm -rf /etc/VpsPackdir/fecha 2>/dev/null
rm -rf /root/name 2>/dev/null
rm -rf /bin/limite 2>/dev/null
wget -o /dev/null -O- https://www.dropbox.com/s/1t17ym8fs9c4ban/limite > /bin/limite
chmod +x /bin/limite
rm -rf /etc/VpsPackdir/bbrplus.sh 2>/dev/null
wget -o /dev/null -O- https://www.dropbox.com/s/2kvu7r6s1agoal1/bbrplus.sh > /etc/VpsPackdir/bbrplus.sh
chmod +x /etc/VpsPackdir/bbrplus.sh
rm -rf /etc/VpsPackdir/sslhconf 2>/dev/null
wget -o /dev/null -O- https://www.dropbox.com/s/p2bu2gycd4p0hjb/sslhconf > /etc/VpsPackdir/sslhconf
chmod +x /etc/VpsPackdir/sslhconf
rm -rf /bin/criarusuario
wget -o /dev/null -O- https://www.dropbox.com/s/9pog1pohyjsigfw/criarusuario > /bin/criarusuario
chmod +x /bin/criarusuario
rm -rf /bin/deletarusuario
wget -o /dev/null -O- https://www.dropbox.com/s/uqijj207x1ach92/deletarusuario > /bin/deletarusuario
chmod +x /bin/deletarusuario
rm -rf /bin/redefinirusuario
wget -o /dev/null -O- https://www.dropbox.com/s/kjjcv1us3tp5bxa/redefinirusuario > /bin/redefinirusuario
chmod +x /bin/redefinirusuario
rm -rf /bin/vpspack
wget -o /dev/null -O- https://www.dropbox.com/s/pcm1manlhcneun1/vpspack > /bin/vpspack
chmod +x /bin/vpspack
rm -rf /bin/speedtest.py
wget -o /dev/null -O- https://www.dropbox.com/s/ro0nc7jsj6zo3jo/speedtest.py > /bin/speedtest.py
chmod +x /bin/speedtest.py
rm -rf /bin/toolmaster
wget -o /dev/null -O- https://www.dropbox.com/s/yhzsmb6b4geh3wa/toolmaster > /bin/toolmaster
chmod +x /bin/toolmaster
rm -rf /etc/VpsPackdir/pl.sh
wget -o /dev/null -O- https://www.dropbox.com/s/8nzogjbtb0fii8z/pl.sh > /etc/VpsPackdir/pl.sh
chmod +x /etc/VpsPackdir/pl.sh
rm -rf /etc/VpsPackdir/d.sh
wget -o /dev/null -O- https://www.dropbox.com/s/fhy2zolblx9emgy/d.sh > /etc/VpsPackdir/d.sh
chmod +x /etc/VpsPackdir/d.sh
rm -rf /root/dropbear
wget -o /dev/null -O- https://www.dropbox.com/s/s8va52zhx7k9kvd/dropbear > /root/dropbear
rm /etc/VpsPackdir/ssl
wget -o /dev/null -O- wget https://www.dropbox.com/s/3o14tavtdt89atp/ssl > /etc/VpsPackdir/ssl
rm -rf /etc/VpsPackdir/shadowsocks.sh
wget -o /dev/null -O- wget https://www.dropbox.com/s/qp9pr9yfzxrm4c0/shadowsocks.sh > /etc/VpsPackdir/shadowsocks.sh
chmod +x /etc/VpsPackdir/shadowsocks.sh
rm -rf /root/proxy.py
wget -o /dev/null -O- wget https://www.dropbox.com/s/3r18gyzapqux2yx/proxy.py > /root/proxy.py
rm -rf /etc/VpsPackdir/open-vpn-install.sh
wget -o /dev/null -O- wget https://www.dropbox.com/s/cctoq8sweqhm062/openvpn-install.sh > /etc/VpsPackdir/openvpn-install.sh
chmod +x /etc/VpsPackdir/openvpn-install.sh
rm -rf /etc/VpsPackdir/confdropbear
wget -o /dev/null -O- wget https://www.dropbox.com/s/h9d9iiexwm5skpo/confdropbear > /etc/VpsPackdir/confdropbear
rm -rf /etc/VpsPackdir/dropxbear
wget -o /dev/null -O- wget https://www.dropbox.com/s/uchq8jpw8dsqhce/dropxbear > /etc/VpsPackdir/dropxbear
chmod +x /etc/VpsPackdir/dropxbear
rm -rf /etc/VpsPackdir/danted.conf
wget -o /dev/null -O- wget https://www.dropbox.com/s/m38q4cf4oaigcs0/danted.conf > /etc/VpsPackdir/danted.conf
rm -rf /etc/VpsPackdir/limpieza.sh
wget -o /dev/null -O- wget https://www.dropbox.com/s/9uxws8qmqgw94yo/limpieza.sh > /etc/VpsPackdir/limpieza.sh
chmod +x /etc/VpsPackdir/limpieza.sh
wget -o /dev/null -O- wget https://www.dropbox.com/s/ou9j7noglwe79ld/version > /etc/VpsPackdir/version
if [ -f /etc/banner ];
then
echo "Banner Detectado"
else
wget -o /dev/null -O- wget https://www.dropbox.com/s/wd85e7oe7z15ewp/banner > /etc/banner
fi
chmod +x /root/dropbear
}
fun_bar 'preparar'
function paquetes(){
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m Instalando Paquetes\033[1;33m"
apt-get -y install build-essential 1> /dev/null 2> /dev/null
apt-get -y install nano 1> /dev/null 2> /dev/null
apt-get -y install net-tools 1> /dev/null 2> /dev/null
apt-get -y install iptables 1> /dev/null 2> /dev/null
apt-get -y install unzip 1> /dev/null 2> /dev/null
apt-get -y install htop 1> /dev/null 2> /dev/null
apt-get -y install curl 1> /dev/null 2> /dev/null
apt-get -y install nginx 1> /dev/null 2> /dev/null
apt-get -y install figlet 1> /dev/null 2> /dev/null
apt-get -y install git 1> /dev/null 2> /dev/null
apt-get -y install build-essential libpq-dev libssl-dev openssl libffi-dev zlib1g-dev 1> /dev/null 2> /dev/null
apt-get -y install screen 1> /dev/null 2> /dev/null
apt-get -y install python3-pip 1> /dev/null 2> /dev/null
apt-get -y install python-pip 1> /dev/null 2> /dev/null
apt-get -y install nload 1> /dev/null 2> /dev/null
apt-get -y install dos2unix 1> /dev/null 2> /dev/null
apt-get -y install npm 1> /dev/null 2> /dev/null
yum -y install figlet nano unzip curl 1> /dev/null 2> /dev/null
service apache2 stop 1> /dev/null 2> /dev/null
if cat /etc/apt/sources.list |grep neofetch 1> /dev/null 2> /dev/null; then
echo -e "Ya esta instalado Neofetch"
else
echo "deb http://dl.bintray.com/dawidd6/neofetch jessie main" | sudo tee -a /etc/apt/sources.list
curl -L "https://bintray.com/user/downloadSubjectPublicKey?username=bintray" -o Release-neofetch.key && sudo apt-key add Release-neofetch.key && rm Release-neofetch.key
apt-get update 1> /dev/null 2>/dev/null
apt-get install -y neofetch 1> /dev/null 2> /dev/null
fi
rm /etc/nginx/sites-enabled/default 1> /dev/null 2>/dev/null
rm /etc/nginx/sites-available/default 1> /dev/null 2>/dev/null
wget --no-check-certificate -O /etc/nginx/nginx.conf "https://www.dropbox.com/s/5lcqsxb7dmlhy2d/nginx.conf" 1> /dev/null 2> /dev/null
mkdir -p /home/vps/public_html 1> /dev/null 2> /dev/null
echo "<pre>VPSPACK $vpspackversion</pre>" > /home/vps/public_html/index.html 1> /dev/null 2> /dev/null
wget --no-check-certificate -O /etc/nginx/conf.d/vps.conf "https://www.dropbox.com/s/702utxwr1bhn1fm/vps.conf" 1> /dev/null 2> /dev/null
service nginx restart
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m Instalacion Finalizada\033[1;33m"
}
fun_bar 'paquetes'
sleep 5
clear
if cat /root/.bashrc | grep VPSPack; then
echo -e ":)"
else
echo "clear" >> .bashrc
echo 'DATE=$(date +"%d-%m-%y")' >> .bashrc
echo 'TIME=$(date +"%T")' >> .bashrc
echo 'figlet -k VPSPack' >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e "Nombre del Servidor : $HOSTNAME"' >> .bashrc
echo 'echo -e "Fecha del Servidor : $DATE"' >> .bashrc
echo 'echo -e "Hora del Servidor : $TIME"' >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e "Bienvenido!"' >> .bashrc
echo 'echo -e "Teclee vpspack para ver el listado de comandos."' >> .bashrc
echo 'echo -e ""' >> .bashrc
fi
clear
cat /etc/VpsPackdir/logo
echo -e "\033[1;32mInstalacion Finalizada\n\033[1;30m"
echo -e "\n\033[1;32mvpspack     \033[1;30mMENU DE OPCIONES"
echo -e "\033[1;32mOpcion 1    \033[1;30mINSTALAR SQUID/SSH"
echo -e "\033[1;32mOpcion 2    \033[1;30mADMINISTRACION DE USUARIOS"
echo -e "\033[1;32mOpcion 8    \033[1;30mPUERTOS HABILITADOS"
echo -e "\033[1;32mOpcion 10   \033[1;30mINSTALADORES"
echo -e "\033[1;32m@- \033[1;30mGrupo de Telegram : @PwrMX\033[0m"
echo -e "\033[1;32mVersion     \033[1;30m$vpspackversion \033[0m"
echo -e "\033[1;32m Personalizacion - Escribe tu Nick:\033[0m"
echo -e "\033[1;32m (Maximo 10 Caracteres)\033[0m"
read -p ": " nickname
echo "$nickname" >> /root/name
rm -rf g
vpspack
